###############################################################################
#
# ZApache Monitor Toolkit Configuration
#
###############################################################################

VERSION="2.0.0"

STATUS_URL="http://127.0.0.1/server-status?auto"

LOGFILE="/var/log/httpd/internet-access.log"

TIMEOUT=5

TAIL_LINES=5000

HTTP_CLIENT="AUTO"

DEBUG=0

VERBOSE=0
